address: "mongodb://prodMyCarenestReadWrite:#2801Y2kcompProd#MyCarenestReadWrite1082#@103.67.236.142:27017/mycarenest?retryWrites=true"
database: mycarenest
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
