server:
  port: 9004
address:  "mongodb://tiwarri123:typhoon#2206@cluster0-shard-00-00-fm8nd.mongodb.net:27017,cluster0-shard-00-01-fm8nd.mongodb.net:27017,cluster0-shard-00-02-fm8nd.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true"
database: test
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
