eureka:
  client:
     service-url:
        defaultZone: http://103.67.236.142:8761/eureka
     register-with-eureka: true
     fetch-registry: true
  instance:
    hostname: 103.67.236.142
  environment: Prod
  datacenter: Prod DC
