spring:
  profiles:
    active:
    - qa

  cloud:
    config:
      uri: http://localhost:8888/config-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
