spring:
  data:
    mongodb:
      uri: "mongodb://prodMyCarenestReadWrite:#2801Y2kcompProd#MyCarenestReadWrite1082#@103.67.236.142:27017/mycarenest?retryWrites=true"
security:
  oauth2:
    resource:
      token-info-uri: http://103.67.236.142:8080/oauth/check_token
    client:
      client-id: client1
      client-secret: client1pwd
      user-authorization-uri: http://103.67.236.142:8080/oauth/authorize
default:
  distanceInKM: 5
