management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9003
spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: "mongodb://tiwarri123:typhoon#2206@cluster0-shard-00-00-fm8nd.mongodb.net:27017,cluster0-shard-00-01-fm8nd.mongodb.net:27017,cluster0-shard-00-02-fm8nd.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true"
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    
defaultPageIndex: 0
defaultPageSize: 2
defaultPharmacyPageSize: 10
